# A name for your workflow, which will appear in the "Actions" tab of your GitHub repo
name: AI-IDS CI/CD Pipeline

# --- Triggers: When this workflow will run ---
on:
  # Run on every push to the 'develop' branch
  push:
    branches: [ develop ]
  # Also run on pull requests targeting the 'main' branch
  pull_request:
    branches: [ main ]

# --- Jobs: The sequence of tasks to perform ---
jobs:
  build-and-test:
    # Use the latest version of Ubuntu as the virtual machine
    runs-on: ubuntu-latest

    # --- Steps: The individual commands to execute ---
    steps:
      # 1. Check out your repository's code so the workflow can access it
      - name: Check out code
        uses: actions/checkout@v4

      # 2. Set up the Python environment
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Scapy requires libpcap-dev on the system
          sudo apt-get update && sudo apt-get install -y libpcap-dev
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install flake8 pytest # Install testing tools

      # 4. Lint with flake8 (Check for style issues)
      - name: Lint with flake8
        run: |
          # Stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      # 5. Run tests with pytest
      - name: Test with pytest
        run: |
          pytest