name: AI-IDS CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10 with pip cache
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: |
            requirements.txt
            requirements-dev.txt

      - name: System deps (pcap)
        run: |
          sudo apt-get update
          sudo apt-get install -y libpcap-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
          # dev/test tools (kept here to make CI reproducible)
          pip install flake8 mypy bandit pytest pytest-cov

      - name: Lint (flake8)
        run: flake8 .

      - name: Type check (mypy)
        run: |
          mypy --ignore-missing-imports --pretty anomaly_detector.py packet_processor.py network_monitor.py main.py

      - name: Security scan (bandit)
        run: bandit -q -r .

      - name: CLI smoke tests (help screens)
        run: |
          python -m main --help
          python main.py train --help
          python main.py monitor --help

      - name: Unit tests + Coverage (fail <75%)
        run: |
          pytest -q --maxfail=1 --disable-warnings \
            --cov=. --cov-report=xml --cov-report=html --cov-fail-under=75

      - name: Upload coverage artifact (HTML + XML)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            coverage.xml
            htmlcov/

      - name: Build distribution (if pyproject.toml present)
        if: ${{ hashFiles('pyproject.toml') != '' }}
        run: |
          pip install build
          python -m build

      - name: Upload dist artifacts
        if: ${{ hashFiles('pyproject.toml') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: python-dist
          path: dist/
